### ISSUE TITLE
Clarabel vs SCS performance issue on SDPs

### ISSUE THREAD

**Issue by husisy** [cvxpy/cvxpy#2257] opened 2023-10-11 05:39 UTC
Hi, I notice a significant performance degradation (about 100x) in some semi-definite programming (SDP) when upgrading cvxpy from `1.3.x` to `1.4`.

(I tried to minimize this working example as much as possible) The colab link is here [colab/cvxpy-1.4-SDP-performance](https://colab.research.google.com/drive/1JOZH_QWoVOabrdoE3LrSTb0QoTIMJVJE?usp=sharing) and you can run it directly in the browser.

The time usage on colab is as follows:

| hyper-parameter $(d,k)$ | cvxpy-1.3.2 time (s) | cvxpy-1.4.0 time (s) |
| :-: | :-: | :-: |
| (3,3) | 0.0755 | 13.5 |
| (2,5) | 0.252 | 21.2 |

**Expected behavior**: the performance of cvxpy-1.4.0 should be similar to cvxpy-1.3.2

**Version**: Google colab runtime, cvxpy-1.4.0, cvxpy-1.3.2

**Additional context**: The SDP is formulated as follows: given a $d\times d$ semi-definite positive matrix $\sigma$, we are going to find a symmetric semi-definite positive $\rho\in\mathbb{C}^{d^k\times d^k}$ such that its partial trace gives $\sigma$.

$$ \mathrm{find } \rho $$

such that

$$ \rho\succeq0 $$

$$ \mathrm{Tr}_{d^{k-1}}\left[\rho\right]=\sigma $$

$$ P_{ij}\rho P_{ij}=\rho \;i,j\in[k] $$

where $P_{ij}$ is a permutation matrix interchanging the $i$-th and $j$-th partite.

**Comment by aszekMosek** [comment] 2023-10-11 08:35
A simple enabling of verbosity reveals that the new default solver Carabel is responsible for the time increase. Just go back to SCS and you will have the same times as before.

**Comment by husisy** [comment] 2023-10-11 13:53
Thank you for the suggestion. Switching to `prob.solve(solver='SCS')` indeed resolves the speed issue.

I've noticed that cvxpy is transitioning to "Clarabel" as its default solver. Can we anticipate that, in the near future, "Clarabel" will match or even surpass the speed of "SCS"? Introducing `solver="SCS"` throughout my code doesn't seem like the most sustainable solution, especially if "Clarabel" is the direction the library is taking.

**Comment by rileyjmurray** [comment] 2023-10-11 14:31
We expect Clarabel’s SDP performance to improve. That said, there’s a real
chance that Clarabel will still end up being slower than SCS. I say this
because Clarabel computes much more accurate solutions than SCS by default.

Ping @PTNobel.

**Comment by husisy** [comment] 2023-10-11 14:48
got it, thx for your information.

**Comment by rileyjmurray** [comment] 2023-10-11 15:13
Actually, I'm going to reopen the issue with a different title. This is worth investigating more on our end.

**Comment by goulart-paul** [comment] 2023-10-11 15:51
You are correct that it should not get called automatically for SDPs.  Indeed, at present it should not get called automatically ever.    I will fix and make a PR ASAP.

I'll also try to fix the Colab issue separately.

**Comment by goulart-paul** [comment] 2023-10-11 15:54
@husisy As a separate matter, it seems problematic to me that the performance difference vs SCS should be so huge.  If you are willing to do so, we would appreciate seeing an example SDP that does that for benchmarking purposes.   You could make it as an issue here: https://github.com/oxfordcontrol/Clarabel.rs

**Comment by SteveDiamond** [comment] 2023-10-11 16:02
I found the cause. cvxpy/reductions/solvers/defines.py L75 we have
```
CONIC_SOLVERS = [s.MOSEK, s.ECOS, s.CLARABEL, s.SCS, s.SDPA,
                 s.CPLEX, s.GUROBI, s.COPT, s.GLPK, s.NAG,
                 s.GLPK_MI, s.CBC, s.CVXOPT, s.XPRESS, s.DIFFCP,
                 s.SCIP, s.SCIPY, s.GLOP, s.PDLP, s.ECOS_BB]
```
This is the order of preference for solvers. And QP solvers are preferred to conic solvers. So we need to move Clarabel back in the preference order behind SCS.

**Comment by goulart-paul** [comment] 2023-10-11 16:22
NB: #2259 should fix the solver ordering issue using the fix suggested by @SteveDiamond, but doesn't fix the printing problem.   This issue should remain open until both are resolved.

**Comment by PTNobel** [comment] 2023-10-11 18:04
Reopening per Paul's request that we keep it open while figuring out what's causing the issue with Colab verbose output.

**Comment by goulart-paul** [comment] 2023-10-11 19:15
The problem with verbose output seems unrelated to cvxpy, since it also happens with the solver direct python interface.   I opened an issue for it here: https://github.com/oxfordcontrol/Clarabel.rs/issues/60

@PTNobel Fine to close this one if you like.

**Closed** 2023-10-11 19:31 UTC
