### ISSUE TITLE
inv_prod can result in TypeError at Dcp2Cone stage

### ISSUE THREAD

**Issue by GrayThomas** [cvxpy/cvxpy#1581] opened 2021-12-17 20:16 UTC
**Describe the bug**
In cvxpy-1.1.17, with Python3.7, using inv_prod with two or three elements resulted in a TypeError:

`/fractions.py", line 559, in __hash__
    dinv = pow(self._denominator, _PyHASH_MODULUS - 2, _PyHASH_MODULUS)
TypeError: unsupported operand type(s) for pow(): 'numpy.int64', 'int', 'int'
`
**To Reproduce**
```
import cvxpy as cp

DEMONSTRATE_BUG = True

A = cp.Variable()
B = cp.Variable(pos=True)
obj = cp.Minimize(B)
cons = [] 
C = cp.Variable(2, pos=True)
cons.append(C[0] == A)
cons.append(C[1] == A)

if DEMONSTRATE_BUG:
	cons.append(B >= (cp.inv_prod(C)) ) 
else: # demonstrate workaround
	cons.append(B >= cp.power(cp.inv_pos(cp.geo_mean(C)),2) ) # from https://www.cvxpy.org/_modules/cvxpy/atoms/inv_prod.html#inv_prod

prob = cp.Problem(obj,cons)
prob.solve(verbose=True)
```

**Expected behavior**
In theory, the behavior should be identical between DEMONSTRATE_BUG=True or False.

**Output**
```
===============================================================================
                                     CVXPY                                     
                                    v1.1.17                                    
===============================================================================
(CVXPY) Dec 17 03:06:15 PM: Your problem has 4 variables, 3 constraints, and 0 parameters.
(CVXPY) Dec 17 03:06:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Dec 17 03:06:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Dec 17 03:06:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Dec 17 03:06:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Dec 17 03:06:15 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Dec 17 03:06:15 PM: Applying reduction Dcp2Cone
Traceback (most recent call last):
  File "/home/gray/wk/2021SpringDesignPaper/optimization/simple_bug.py", line 20, in <module>
    prob.solve(verbose=True)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 472, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 966, in _solve
    solver, gp, enforce_dpp, verbose)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 626, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/dcp2cone/dcp2cone.py", line 43, in apply
    return super(Dcp2Cone, self).apply(problem)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/canonicalization.py", line 68, in apply
    constraint)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/canonicalization.py", line 99, in canonicalize_tree
    canon_arg, c = self.canonicalize_tree(arg)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/canonicalization.py", line 102, in canonicalize_tree
    canon_expr, c = self.canonicalize_expr(expr, canon_args)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/canonicalization.py", line 113, in canonicalize_expr
    return self.canon_methods[type(expr)](expr, args)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/dcp2cone/atom_canonicalizers/power_canon.py", line 43, in power_canon
    return t, gm_constrs(x, [t, ones], w)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/utilities/power_tools.py", line 65, in gm_constrs
    tree = decompose(w)
  File "/home/gray/anaconda3/lib/python3.7/site-packages/cvxpy/utilities/power_tools.py", line 597, in decompose
    if t not in tree:
  File "/home/gray/anaconda3/lib/python3.7/fractions.py", line 559, in __hash__
    dinv = pow(self._denominator, _PyHASH_MODULUS - 2, _PyHASH_MODULUS)
TypeError: unsupported operand type(s) for pow(): 'numpy.int64', 'int', 'int'
```
**Version**
 - OS: Linux Mint 19.3
 - CVXPY Version: 1.1.17

**Additional context**
But also occurs in Python3.9

**Comment by SteveDiamond** [comment] 2021-12-17 23:19
The issue is that a power atom is being created with a power of type ``np.int64``. This breaks code later involving fractions. The bug can be fixed by changing line
https://github.com/cvxpy/cvxpy/blob/82492d83255452c5b8e744147202289766a5d2f8/cvxpy/atoms/inv_prod.py#L38
to ``return power(inv_pos(geo_mean(value)), int(sum(value.shape)))``.

@akshayka @rileyjmurray should we deploy that fix or add broader input checking to ``power``?

**Closed** 2022-02-03 19:17 UTC
