### ISSUE TITLE
Constant.is_psd() not working on singular matrix

### ISSUE THREAD

**Issue by xialulee** [cvxpy/cvxpy#1469] opened 2021-08-31 08:48 UTC
**Describe the bug**
Hi everyone, years ago I wrote a piece of code to solve a problem of which the objective function is a quad_form. The code runs smoothly with following output (CVXPY 1.0.21):
```
----------------------------------------------------------------------------
	SCS v2.1.4 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 2813
eps = 1.00e-04, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
acceleration_lookback = 10, rho_x = 1.00e-03
Variables n = 257, constraints m = 443
Cones:	primal zero / dual free vars: 210
	linear vars: 1
	soc vars: 22, soc blks: 1
	sd vars: 210, sd blks: 1
Setup time: 5.64e-03s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 4.58e+19  1.17e+20  1.00e+00 -1.90e+21  2.36e+21  5.41e+21  4.80e-03 
   100| 1.03e-03  5.47e-04  2.42e-04  1.31e+01  1.31e+01  8.85e-16  2.49e-02 
   140| 7.44e-05  4.99e-05  6.20e-05  1.31e+01  1.31e+01  1.29e-15  3.31e-02 
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 3.32e-02s
	Lin-sys: nnz in L factor: 3838, avg solve time: 7.10e-06s
	Cones: avg projection time: 3.77e-05s
	Acceleration: avg step time: 1.46e-04s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 1.9019e-16, dist(y, K*) = 1.8934e-09, s'y/|s||y| = 7.1036e-13
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 7.4450e-05
dual res:   |A'y + c|_2 / (1 + |c|_2) = 4.9888e-05
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 6.1957e-05
----------------------------------------------------------------------------
c'x = 13.0637, -b'y = 13.0621
============================================================================
```
However, after I updated cvxpy to the newest version, I cannot solve the problem anymore, cvxpy tells me that my problem does not follow DCP rules. 
```
===============================================================================
                                     CVXPY                                     
                                    v1.1.15                                    
===============================================================================
(CVXPY) Aug 31 04:25:38 PM: Your problem has 201 variables, 4 constraints, and 0 parameters.
(CVXPY) Aug 31 04:25:38 PM: It is compliant with the following grammars: 
(CVXPY) Aug 31 04:25:38 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 31 04:25:38 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
  File "C:\Users\Lee\algorithms.py", line 101, in solve
    self.__problem.solve(*args, **kwargs)  
  File "C:\ProgramData\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 462, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 949, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "C:\ProgramData\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 570, in get_problem_data
    solving_chain = self._construct_chain(
  File "C:\ProgramData\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 798, in _construct_chain
    return construct_solving_chain(self, candidate_solvers, gp=gp,
  File "C:\ProgramData\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 155, in construct_solving_chain
    reductions = _reductions_for_problem_class(problem, candidates, gp)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 91, in _reductions_for_problem_class
    raise DCPError(
cvxpy.error.DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
QuadForm(var1, [[ 1.11049417e-01 -1.11049417e-01 -2.11200807e-01 ... -2.11200807e-01
  -5.76205228e-04 -1.11049417e-01]
 [-1.11049417e-01  1.00000000e+00 -6.09256990e-01 ... -6.09256990e-01
   1.66803418e-16  1.00000000e+00]
 [-2.11200807e-01 -6.09256990e-01  2.44141970e+00 ...  2.44141970e+00
   6.62623993e-17 -6.09256990e-01]
 ...
 [-2.11200807e-01 -6.09256990e-01  2.44141970e+00 ...  2.44141970e+00
   9.38166736e-17 -6.09256990e-01]
 [-5.76205228e-04  1.66803418e-16  6.62623993e-17 ...  9.38166736e-17
   1.55858030e+00  2.83219693e-16]
 [-1.11049417e-01  1.00000000e+00 -6.09256990e-01 ... -6.09256990e-01
   2.83219693e-16  1.00000000e+00]])
```
I am very confused because I am not a mathematician. I check the eigen values of the matrix of the quad form, and it is positive semi definite. 

Thank you in advance.

**Version**
 - OS: Windows 10 
 - CVXPY Version: 1.1.15

**Comment by xialulee** [comment] 2021-08-31 12:49
On 1.0.21, is_dcp returns True:
In [1]: from scipy.io import loadmat

In [2]: Gamma = loadmat('./gamma.mat')['Gamma']

In [3]: import cvxpy as cp

In [4]: rho = cp.Variable(101)

In [5]: cp.quad_form(rho, Gamma)
Out[5]: Expression(CONVEX, NONNEGATIVE, (1, 1))

In [6]: cp.quad_form(rho, Gamma).is_dcp()
Out[6]: True

But on 1.1.15, it returns False:
In [6]: cp.quad_form(rho, Gamma).is_dcp()
Out[6]: False

[gamma.csv](https://github.com/cvxpy/cvxpy/files/7083984/gamma.csv)
I uploaded the matrix (mat file is not allowed, so I uploaded a csv file. )

**Comment by xialulee** [comment] 2021-09-01 02:51
I think I found a temporary solution. Just change the EIGVAL_TOL, and everything goes fine. 
`
import cvxpy as cp

try:
    tol_backup = cp.expressions.constants.constant.EIGVAL_TOL
    cp.expressions.constants.constant.EIGVAL_TOL = 1e-6
    from scipy.io import loadmat
    Gamma = loadmat('c:/lab/gamma.mat')['Gamma']
    result = cp.Constant(Gamma).is_psd()
    print(result)
    rho = cp.Variable(101)
    result = cp.quad_form(rho, Gamma).is_dcp()
    print(result)
finally:
    cp.expressions.constants.constant.EIGVAL_TOL = tol_backup
`

**Comment by SteveDiamond** [comment] 2021-09-02 19:45
@rileyjmurray could you take a look?

**Comment by rileyjmurray** [comment] 2021-09-03 04:07
I can confirm the issue. The matrix ``Gamma`` is singular, and numerically has negative eigenvalues on the order of ``-1e-14``. Changing ``EIGVAL_TOL`` is one way forward here. Another way is to add a small diagonal to ``Gamma``. I added ``1e-11`` to the diagonal and then ``result.is_psd()`` was True.

Unfortunately, I can't look into this in any more detail. I've tried to work on this twice. The fact that this issue persists means that we're looking at some combination of (1) me making mistakes repeatedly, and (2) this problem is actually hard, given only the functions available to us in SciPy. In either case, I don't think I'm the right person to dig deeper.

I'll note that with the csv format, I loaded the matrix into python by
```
Gamma = np.genfromtxt('gamma.csv', delimiter=',')
```

**Comment by xialulee** [comment] 2021-09-03 07:23
Thank you for your reply. I think you suggestion (add a small number to diagonal) is better than modifing EIGVAL_TOL because EIGVAL_TOL is a global setting, and I have to warn my customers not to run the solver in multiple threads if my code changes EIGVAL_TOL temporarily. 
Also, may I suggest that for singular matrices, use numpy.linalg.matrix_rank to filter out the eigen values which are close to zero. 
```python
In [17]: from numpy.linalg import eig, matrix_rank

In [18]: matrix_rank(Gamma)
Out[18]: 20

In [19]: d, V = eig(Gamma)

In [20]: d[:20]
Out[20]:
array([4.39748082e+01+0.j, 1.87319619e+01+0.j, 1.48068937e+01+0.j,
       1.35283339e+01+0.j, 1.15903829e+01+0.j, 1.13461068e+01+0.j,
       1.69838285e-02+0.j, 1.66473510e+00+0.j, 1.63741938e+00+0.j,
       9.88105826e+00+0.j, 9.71076713e+00+0.j, 7.65039047e+00+0.j,
       8.19658921e+00+0.j, 8.10100965e+00+0.j, 3.29718782e+00+0.j,
       3.25365328e+00+0.j, 6.48367024e+00+0.j, 6.55500046e+00+0.j,
       4.92659954e+00+0.j, 4.86854712e+00+0.j])
```

**Comment by xialulee** [comment] 2021-09-03 09:14
Following the suggestion, I add a small number to the diagonal of Gamma, and I designed an equation to determine the value of the small number adaptively:
δ = 10**(2/3*log10(-min_ev))
I test it in several typical cases, and it runs smoothly. I hope that  it will solve all the problems and satisfy my bad tempered customers. 

The complete code for generating Gamma using this equation:
```hy
(defn matG [M angles magnitude]
    (setv N (len angles) )
    (setv A (matA M angles) ) 
    (setv P (matP M) ) 
    (setv G (
        ∑ #_< [a m] ∈ (zip A.T magnitude) #_> (do
            (▦→┇ a)
            (setv t (->> a
                (.conj) 
                (kron a) 
                (@ P.T) 
                (-) ) ) 
            (setv g #┇[m t])
            (. (outer g g) real) ) ) ) 
    (/= G N) 
    (setv min-ev (-> G (eigvals) (real) (min)))
    (when (< min-ev 0.0)
        (setv 
            -min-ev (- min-ev)
            _2/3    (/ 2 3))
        (setv δ (** 10 (* _2/3 (log10 -min-ev))))
        (setv M²+1 (inc (** M 2)))
        (+= G (* δ (eye M²+1))))
    G)
```

**Comment by xialulee** [comment] 2021-09-03 09:28
I have several ideas:
1. Provide an option to bypass the DCP test (because in many cases the user can guarantee that their problem is convex);
2. Design a different criterion for singular matrices (using matrix_rank to filter out eigvals close to zero);
3. Provide a method to change EIGVAL_TOL locally without changing the global settings. 
I don't know whether they are feasible, but I think these ideas may make cvxpy more friendly, because singular matrices are very common in engineering problems.

**Comment by rileyjmurray** [comment] 2021-09-03 12:51
@xialulee we don't want to use ``matrix_rank`` because that computes the SVD of a matrix. Algorithms for computing SVD produce dense matrices, while the eigenvalue checks we perform use an iterative method that's suitable for sparse matrices. I don't understand the code you provided in your second comment. What language is that? Could you maybe write out the algorithm you're using in pseudo-code?

For your three ideas:
 1. I don't think we can do that easily. However, I do think it would be nice if we had that functionality.
 2. From my comment above -- rank determination is hard because we need the method to work efficiently for sparse matrices.
 3. This could probably be done relatively easily. Python's "with" construction is used for similar purposes in other settings.

Finally, just to explain why modifying the diagonal can produce better results than changing ``EIGVAL_TOL``: the iterative algorithm we use doesn't compute the smallest eigenvalue directly. It computes the eigenvalue(s) of a shifted (and I think also inverted) version of the matrix. Then we perform a check on the smallest eigenvalue which fails if and only if the original matrix had an eigenvalue that falls outside of our tolerance. However, if the iterative method does not *accurately* compute the relevant eigenvalue of the shifted (and inverted) matrix, then inaccuracies there can (effectively) get magnified when we run our eigenvalue check. These subtleties are explained in comments of the relevant cvxpy source code.

**Comment by xialulee** [comment] 2021-09-03 17:13
My code is written in Hy, a lisp dialect running on Python runtime. The Python version of my code looks like:
```python
# Calculating G based on some theory I already forgot. 
# G cannot pass the psd test 
# because it has very small negative eigvals.
# Newly added code to solve the problem:
min_ev = min(eigvals(G))
if min_ev < 0.0:
    # determine the small value:
    delta = 10 ** (2/3 * log10(-min_ev))
    # add the small value to the diagonal of G
    G += delta * eye(delta.shape[0])
return G
```
I tested it on several realistic scenarios, ALL SUCCESS.
Thank you sir. You saved my weekend. May I close the issue?

**Comment by rileyjmurray** [comment] 2021-09-03 18:13
I see. If that solution works for you (and it should be fine for n-by-n matrices with n < 500), then that's great. I'll take care of closing the issue. Before I do that, I want to create a new issue that describes the need for a more robust ``Constant.is_psd()``. (Keeping this issue open will help make sure I don't forget to create a new one.)

**Closed** 2021-11-08 23:43 UTC
