### ISSUE TITLE
The c-extension module _multiarray_umath is new to numpy 1.16.0

### ISSUE THREAD

**Issue by ringyear** [cvxpy/cvxpy#968] opened 2020-03-17 09:45 UTC
**Describe the bug**
The doc specified that it depends on numpy>=1.15, but it not true.

**To Reproduce**
I have installed numpy==1.15.2, and then I installed the latest version of CVXPY(1.0.28), it will goes wrong when importing the library.

**Expected behavior**
It should update the requirements.

**Version**
 - OS:  Linux
 - CVXPY Version: v1.0.28 or lastest version

**Attachment**
Ref: https://numpy.org/devdocs/release/1.16.0-notes.html#umath-and-multiarray-c-extension-modules-merged-into-a-single-module
![1](https://user-images.githubusercontent.com/5770579/76852554-90a72180-6886-11ea-9fcb-16e0b3572d36.png)

**Comment by brettplarson** [comment] 2020-03-20 19:04
Which version of CVXPY and numpy should be used?

**Comment by ringyear** [comment] 2020-03-20 19:22
> Which version of CVXPY and numpy should be used?

It seems that cvxpy>=1.0.1 depdends on numpy>=1.16.0 under Linux.

**Comment by rileyjmurray** [comment] 2020-03-20 19:28
Version 1.0.28 was built successfully with numpy 1.15.4 ([OSX build log](https://travis-ci.org/github/cvxgrp/cvxpy/jobs/654669516), [Linux build log](https://travis-ci.org/github/cvxgrp/cvxpy/jobs/654669520)). The error you're seeing here happens from time to time. From the most recent issue (#935), the solution was to uninstall cvxpy and numpy, and then (1) install numpy, (2) install cvxpy -- the order of installation is important. Give that a shot and post again here if that doesn't work.

**Comment by rileyjmurray** [comment] 2020-03-29 19:24
@brettplarson can you please let us know if my earlier comment fixed your problem?

@ringyear can you explain your comment regarding cvxpy >= 1.0.1 and numpy >= 1.16 on linux?

**Comment by ringyear** [comment] 2020-03-30 03:29
@rileyjmurray , I have tried your suggestion days ago, but it seems not working. and I did the following test.
step1: pip3 install numpy==1.15.2
step2: pip3 install cvxpy==1.0.28 (not working, raised _multiarray_umath error)
step3: pip3 install numpy==1.16.0 (worked now)

It seems that CVXPY (cvxpy.cvxcore.python._cvxcore is some python c extension based on numpy) depends on numpy.core._multiarray_umath, the module introduced in numpy 1.16.0.
It is true that we can build cvxpy==1.0.28 on numpy>=1.15 ，but it will raise the exception while importing it.

**Comment by rileyjmurray** [comment] 2020-03-30 14:22
Thanks for replying @ringyear. I've now replicated the issue on a machine of my own. If I run
```
conda create --name cvxNumpyCheck python=3.7 -y
conda activate cvxNumpyCheck
pip install numpy==1.15.2
pip install scipy
pip install ecos scs osqp
pip install cvxpy==1.0.28
```
then ``python -c "import cvxpy"`` fails with the error message you indicate.

The issue can be replicated when installing cvxpy 1.0.28 from source:
```
mkdir tempcvxpy
cd tempcvxpy
git clone https://github.com/cvxgrp/cvxpy.git
cd cvxpy
git checkout 1.0.28
pip install -e .
```


This is *very* strange, because our build logs for cvxpy 1.0.28 clearly indicate that cvxpy builds and imports successfully with numpy 1.15 (https://travis-ci.org/github/cvxgrp/cvxpy/jobs/654669520#L3429, and back to line 3381).

The issue can't be replicated on conda, since conda updates numpy to version 1.18 when installing cvxpy. (For conda I checked with cvxpy 1.0.25 from the cvxgrp channel and cvxpy 1.0.27 from the conda-forge channel.)

**Comment by akshayka** [comment] 2020-04-10 20:17
We're seeing the same issue in our package diffcp, which depends on CVXPY. When NumPy 1.15.4 is installed, we get the import error.

**Comment by isuruf** [comment] 2020-04-17 02:42
This is because of pip's build isolation feature. Because of the `pyproject.toml` file, pip would create a new temporary environment to build the cvxpy extension and would install the latest numpy there (numpy 1.18.0) and cvxpy will be built using that. After that, the built wheel is installed into the original environment where numpy 1.15 is installed. If an extension using the C API of numpy is built with version `x`, generally at runtime you need numpy `>=x`, but this build isolation mechanism thing is interfering with it. I suggest raising this issue in https://discuss.python.org/c/packaging.

**Comment by isuruf** [comment] 2020-04-17 02:43
Possible workarounds are `pip install cvxpy --no-build-isolation` or deleting `pyproject.toml` file in the root.

**Comment by akshayka** [comment] 2020-04-18 18:31
@isuruf , thanks for the context! That makes things clearer.

@stevediamond (or anyone else who knows enough to chime in): do we need the pyproject.toml file?

**Comment by rileyjmurray** [comment] 2020-04-18 19:03
@akshayka my last comment suggests that build-time vs run-time isn't the core of the issue here. I provided an example where cvxpy 1.0.28 successfully builds from source in an environment with numpy 1.15, but then fails import in that same environment.

**Comment by isuruf** [comment] 2020-04-18 19:15
@rileyjmurray did you try `pip install cvxpy --no-build-isolation` ? It is an issue with build time. `pip` will create a new temporary environment different from what you have in conda.

**Comment by SteveDiamond** [comment] 2020-04-18 19:28
@akshayka I'm not sure if pyproject.toml is necessary. @isuruf would probably know more about that. Anyway, this whole discussion is very helpful. I'm optimistic that we can stop the creep towards higher and higher required NumPy versions, which I never quite understood until now.

**Comment by rileyjmurray** [comment] 2020-04-18 19:37
@isuruf to make sure I know exactly what files I'm working with, I cloned the cvxpy repo into a new directory, checked out 1.0.28, and then ran the analagous command ``pip install . --no-build-isolation``. The following log shows the result of this process (an import error).
```
(base) Rileys-MacBook-Pro:cvxpy RJMurray$ conda activate cvxNumpyCheck
(cvxNumpyCheck) Rileys-MacBook-Pro:cvxpy RJMurray$ pip install numpy==1.15.2 -q
(cvxNumpyCheck) Rileys-MacBook-Pro:cvxpy RJMurray$ pip install scipy -q
(cvxNumpyCheck) Rileys-MacBook-Pro:cvxpy RJMurray$ pip install ecos scs osqp -q
(cvxNumpyCheck) Rileys-MacBook-Pro:cvxpy RJMurray$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.15.2'
>>> quit()
(cvxNumpyCheck) Rileys-MacBook-Pro:cvxpy RJMurray$ pip install . --no-build-isolation
Processing /Users/RJMurray/Desktop/tempcvxpy/moretemp/cvxpy
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.15 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy==1.0.28) (1.15.2)
Requirement already satisfied: scipy>=1.1.0 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy==1.0.28) (1.4.1)
Processing /Users/RJMurray/Library/Caches/pip/wheels/96/20/ac/9f1d164f7d81787cd6f4401b1d05212807d021fbbbcc301b82/multiprocess-0.70.9-cp37-none-any.whl
Requirement already satisfied: osqp>=0.4.1 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy==1.0.28) (0.6.1)
Requirement already satisfied: ecos>=2 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy==1.0.28) (2.0.7.post1)
Requirement already satisfied: scs>=1.1.3 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy==1.0.28) (2.1.2)
Processing /Users/RJMurray/Library/Caches/pip/wheels/59/b1/91/f02e76c732915c4015ab4010f3015469866c1eb9b14058d8e7/dill-0.3.1.1-cp37-none-any.whl
Requirement already satisfied: future in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from osqp>=0.4.1->cvxpy==1.0.28) (0.18.2)
Building wheels for collected packages: cvxpy
  Building wheel for cvxpy (PEP 517) ... done
  Created wheel for cvxpy: filename=cvxpy-1.0.28-cp37-cp37m-macosx_10_9_x86_64.whl size=748044 sha256=804369b6af6d8d1a68a9d0157248de918e3fb3dcd35c5bf34e4fbb8ab5d3d114
  Stored in directory: /private/var/folders/zr/7tngff5x68j9bvh7hcv1wzh40000gn/T/pip-ephem-wheel-cache-94e89y24/wheels/d2/9f/4f/2289c88998495baeed551582f449d5f749fea9833e40c4cb00
Successfully built cvxpy
Installing collected packages: dill, multiprocess, cvxpy
Successfully installed cvxpy-1.0.28 dill-0.3.1.1 multiprocess-0.70.9
(cvxNumpyCheck) Rileys-MacBook-Pro:cvxpy RJMurray$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

I then uninstalled cvxpy, and ran the exact command you recommended (in a folder separate from cvxpy source). Ultimately I see the same error.
```
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ pip install cvxpy --no-build-isolation
Collecting cvxpy
  Downloading cvxpy-1.0.31-cp37-cp37m-macosx_10_9_x86_64.whl (746 kB)
     |████████████████████████████████| 746 kB 2.5 MB/s 
Requirement already satisfied: scs>=1.1.3 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (2.1.2)
Requirement already satisfied: osqp>=0.4.1 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (0.6.1)
Requirement already satisfied: ecos>=2 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (2.0.7.post1)
Requirement already satisfied: multiprocess in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (0.70.9)
Requirement already satisfied: scipy>=1.1.0 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (1.4.1)
Requirement already satisfied: numpy>=1.15 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (1.15.2)
Requirement already satisfied: future in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from osqp>=0.4.1->cvxpy) (0.18.2)
Requirement already satisfied: dill>=0.3.1 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from multiprocess->cvxpy) (0.3.1.1)
Installing collected packages: cvxpy
Successfully installed cvxpy-1.0.31
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ import cvxpy
-bash: import: command not found
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

**Comment by isuruf** [comment] 2020-04-18 19:54
Thanks @rileyjmurray for checking. `osqp` wheels have the same problem.
Can you try the following?
```
pip uninstall cvxpy
pip uninstall osqp
conda instll osqp numpy=1.15
pip install cvxpy --no-build-isolation --no-cache
```

**Comment by isuruf** [comment] 2020-04-18 20:37
Btw, osqp wheels will be fixed by https://github.com/oxfordcontrol/osqp-wheels/pull/3

**Comment by rileyjmurray** [comment] 2020-04-18 21:08
@isuruf I uninstalled cvxpy, osqp, and numpy (all previously from pip). Then I followed your instructions for installing osqp, numpy, and cvxpy. Here's the log from the installation process.

```
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ conda install osqp numpy=1.15
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck

  added / updated specs:
    - numpy=1.15
    - osqp


The following NEW packages will be INSTALLED:

  future             conda-forge/osx-64::future-0.18.2-py37hc8dfbb8_1
  libblas            conda-forge/osx-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/osx-64::libcblas-3.8.0-16_openblas
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-2
  liblapack          conda-forge/osx-64::liblapack-3.8.0-16_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.9-h3d69b6c_0
  llvm-openmp        conda-forge/osx-64::llvm-openmp-10.0.0-h28b9765_0
  numpy              conda-forge/osx-64::numpy-1.15.4-py37hbb3c62a_1002
  osqp               conda-forge/osx-64::osqp-0.6.1-py37h94625e5_2
  scipy              conda-forge/osx-64::scipy-1.4.1-py37hce1b9e5_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ pip install cvxpy --no-build-isolation --no-cache
Collecting cvxpy
  Downloading cvxpy-1.0.31-cp37-cp37m-macosx_10_9_x86_64.whl (746 kB)
     |████████████████████████████████| 746 kB 5.3 MB/s 
Requirement already satisfied: numpy>=1.15 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (1.15.4)
Requirement already satisfied: multiprocess in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (0.70.9)
Requirement already satisfied: scs>=1.1.3 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (2.1.2)
Requirement already satisfied: osqp>=0.4.1 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (0.6.1)
Requirement already satisfied: ecos>=2 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (2.0.7.post1)
Requirement already satisfied: scipy>=1.1.0 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (1.4.1)
Requirement already satisfied: dill>=0.3.1 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from multiprocess->cvxpy) (0.3.1.1)
Requirement already satisfied: future in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from osqp>=0.4.1->cvxpy) (0.18.2)
Installing collected packages: cvxpy
Successfully installed cvxpy-1.0.31
```
Then I tried to run cvxpy, but this produced an error.
```
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```
Here's the state of my conda environment
```
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ conda list
# packages in environment at /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cvxpy                     1.0.31                   pypi_0    pypi
dill                      0.3.1.1                  pypi_0    pypi
ecos                      2.0.7.post1              pypi_0    pypi
future                    0.18.2           py37hc8dfbb8_1    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcxx                    9.0.1                         1    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
llvm-openmp               10.0.0               h28b9765_0    conda-forge
multiprocess              0.70.9                   pypi_0    pypi
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.15.4          py37hbb3c62a_1002    conda-forge
openssl                   1.1.1f               h0b31af3_0    conda-forge
osqp                      0.6.1            py37h94625e5_2    conda-forge
pip                       20.0.2                     py_2    conda-forge
python                    3.7.6           h90870a6_5_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
scipy                     1.4.1            py37hce1b9e5_3    conda-forge
scs                       2.1.2                    pypi_0    pypi
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```

**Comment by isuruf** [comment] 2020-04-18 21:26
Ah, I didn't realize the cvxpy had wheels for macos. Can you do the following?
```
pip uninstall cvxpy
pip install cvxpy --no-binary :all: --no-build-isolation --no-cache
```

**Comment by rileyjmurray** [comment] 2020-04-18 23:19
Here's the output of that one:
```
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ pip uninstall cvxpy
Found existing installation: cvxpy 1.0.31
Uninstalling cvxpy-1.0.31:
  Would remove:
    /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages/_cvxcore.cpython-37m-darwin.so
    /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages/cvxpy-1.0.31.dist-info/*
    /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages/cvxpy/*
    /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages/examples/*
Proceed (y/n)? y                                                                              
  Successfully uninstalled cvxpy-1.0.31

(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ pip install cvxpy --no-binary :all: --no-build-isolation --no-cache
Collecting cvxpy
  Downloading cvxpy-1.0.31.tar.gz (947 kB)
     |████████████████████████████████| 947 kB 3.6 MB/s 
    Preparing wheel metadata ... done
Requirement already satisfied: osqp>=0.4.1 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (0.6.1)
Requirement already satisfied: scipy>=1.1.0 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (1.4.1)
Requirement already satisfied: scs>=1.1.3 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (2.1.2)
Requirement already satisfied: numpy>=1.15 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (1.15.0)
Requirement already satisfied: ecos>=2 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (2.0.7.post1)
Requirement already satisfied: multiprocess in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from cvxpy) (0.70.9)
Requirement already satisfied: future in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from osqp>=0.4.1->cvxpy) (0.18.2)
Requirement already satisfied: dill>=0.3.1 in /Users/RJMurray/opt/anaconda3/envs/cvxNumpyCheck/lib/python3.7/site-packages (from multiprocess->cvxpy) (0.3.1.1)
Building wheels for collected packages: cvxpy
  Building wheel for cvxpy (PEP 517) ... done
  Created wheel for cvxpy: filename=cvxpy-1.0.31-cp37-cp37m-macosx_10_9_x86_64.whl size=748213 sha256=60337521d31da61fa835bd7933b0a42c54e37f1e83b89ec713ab3f3ac37cfe7e
  Stored in directory: /private/var/folders/zr/7tngff5x68j9bvh7hcv1wzh40000gn/T/pip-ephem-wheel-cache-f_bfomd4/wheels/76/a1/09/8911c1eefb1b0e6fb39a9899faebe9c0ec1cd66d9d9fb2742d
Successfully built cvxpy
Installing collected packages: cvxpy
Successfully installed cvxpy-1.0.31

(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

**Comment by isuruf** [comment] 2020-04-19 00:25
`import osqp` works fine?
If so, can you do the following and send me the output?
```
pip uninstall cvxpy
pip install cvxpy --no-binary :all: --no-build-isolation --no-cache --verbose
```
It's going to be a lengthy output. (Maybe put it in a gist?)

**Comment by isuruf** [comment] 2020-04-19 00:33
Here's what I did on OSX to reproduce, but it worked fine.
```
conda create --name cvxNumpyCheck2 "numpy=1.15.*" scipy ecos scs osqp "python=3.7" -y
conda activate cvxNumpyCheck2
pip install cvxpy --no-binary :all: --no-build-isolation --no-cache
python -c "import cvxpy"
```

**Comment by rileyjmurray** [comment] 2020-04-19 00:44
``import osqp`` did work fine on that last run. But I've found something else super weird.
```
(cvxNumpyCheck) Rileys-MacBook-Pro:tempcvxpy RJMurray$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print(np.__version__)
1.15.0
>>> import cvxpy as cp
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
>>> x = cp.Variable(shape=(2,))
>>> prob = cp.Problem(cp.Maximize(cp.sum(x)),[cp.norm(x,2) <= 1])
>>> prob.solve(verbose=True)

ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +0.000e+00  -5.069e+00  +2e+00  6e-03  3e-01  1e+00  1e+00    ---    ---    1  1  - |  -  - 
 1  -1.311e+00  -2.350e+00  +5e-01  1e-03  7e-02  2e-01  2e-01  0.8779  1e-01   2  1  1 |  0  0
 2  -1.399e+00  -1.442e+00  +2e-02  4e-05  3e-03  4e-03  9e-03  0.9598  9e-04   1  1  1 |  0  0
 3  -1.414e+00  -1.415e+00  +3e-04  4e-07  3e-05  5e-05  1e-04  0.9890  1e-04   1  1  1 |  0  0
 4  -1.414e+00  -1.414e+00  +3e-06  5e-09  3e-07  5e-07  1e-06  0.9890  1e-04   1  1  1 |  0  0
 5  -1.414e+00  -1.414e+00  +3e-08  5e-11  4e-09  6e-09  1e-08  0.9890  1e-04   2  1  1 |  0  0
 6  -1.414e+00  -1.414e+00  +3e-10  6e-13  4e-11  7e-11  1e-10  0.9890  1e-04   1  1  1 |  0  0

OPTIMAL (within feastol=4.2e-11, reltol=2.4e-10, abstol=3.4e-10).
Runtime: 0.000217 seconds.

1.4142135621569818
``` 
-- which is to say *cvxpy can run successfully even with this error message???*

**Comment by rileyjmurray** [comment] 2020-04-19 00:52
@isuruf your last sequence of commands (creating the environment and all) ran just fine on my machine. So although I'm very lost as to why all this is happening, it's clear that cvxpy *can* run on numpy 1.15 without any kind of import error (even an inconsequential import error, like the one in my last comment). Thanks for sticking with me through this exchange.

**Comment by SteveDiamond** [comment] 2020-04-19 02:10
@rileyjmurray thanks for investigating this! What are next steps? Do we delete pyproject.toml? Definitely we should avoid bumping the requirement to NumPy 1.16.

**Comment by isuruf** [comment] 2020-04-20 20:10
> Do we delete pyproject.toml? 

Or do something like what scipy does. https://github.com/scipy/scipy/blob/master/pyproject.toml#L6-L11

**Comment by SteveDiamond** [comment] 2020-07-14 06:33
@rileyjmurray Is this fixed? I assume the conda forge build doesn't have this issue?

**Comment by rileyjmurray** [comment] 2020-07-14 16:05
@SteveDiamond I lost track of this issue, to be honest.

I believe this issue has always been isolated to installs from pip. So CVXPY distribution via conda (conda-forge, or the effectively unused cvxgrp channel) should be unaffected.

Isuru suggested the issue was a build-isolation feature related to pip; much of the back-and-forth above was because of particular behavior with macOS wheels. For me the definitive explanation that build-isolation was at the core of the problem is that In Isuru's https://github.com/cvxgrp/cvxpy/issues/968#issuecomment-615992453 works without any kind of import error (including without "inconsequential" import errors like in https://github.com/cvxgrp/cvxpy/issues/968#issuecomment-615994677). I'm inclined to solve this problem by mimicking SciPy, as Isuru mentioned above. Here's [a blog post](https://snarky.ca/what-the-heck-is-pyproject-toml/) explaining ``pyproject.toml`` if you'd like to look into it as well.

**Comment by isuruf** [comment] 2020-07-14 16:34
For the macOS wheels, you'll have to fix osqp-wheels as well. See https://github.com/oxfordcontrol/osqp-wheels/pull/3

**Comment by rileyjmurray** [comment] 2020-12-31 19:35
Just a minor note here, our build process was updated in #1202. No attempt was made to address this issue specifically, but we now use NumPy 1.15, 1.16, and 1.9 for Python 3.7, 3.8, and 3.9 builds respectively. These appear to be the earliest versions of numpy that satisfy our web of dependencies for a given version of python.

**Comment by rileyjmurray** [comment] 2021-12-05 23:39
Our build process was updated again in #1368. We have wheels for all platforms starting with cvxpy 1.1.13 in May 2021. Closing this issue, since it should no longer be relevant.

**Closed by rileyjmurray** 2021-12-05 23:39 UTC
