### ISSUE TITLE
Warning messages: have mixed-integer quadratic programming example recommend SCIP

### ISSUE THREAD

**Issue by sarahboufelja** [cvxpy/cvxpy#1706] opened 2022-03-14 20:52 UTC
**Describe the bug**
Using cvxpy 1.3.0 to solve the same example of MIP shown on the main webpage https://www.cvxpy.org/examples/basic/mixed_integer_quadratic_program.html. The code fails though with the following error: SolverError: 

                    You need a mixed-integer solver for this model. Refer to the documentation
                        https://www.cvxpy.org/tutorial/advanced/index.html#mixed-integer-programs
                    for discussion on this topic.
I have already installed CVXOPT and GLPK solvers but none seems to be recognised by cvxpy. The only solver that works is ECOS_BB, however this solver is not recommended as it produces errors. 

**To Reproduce**
#### Generate a random problem
np.random.seed(0)
m, n= 40, 25

A = np.random.rand(m, n)
b = np.random.randn(m)
#### Construct a CVXPY problem
x = cp.Variable(n, integer=True)
objective = cp.Minimize(cp.sum_squares(A @ x - b))
prob = cp.Problem(objective)
prob.solve()

**Expected behavior**
The code should output the optimal value x of the MIP. 

**Output**
SolverError: 

                    You need a mixed-integer solver for this model. Refer to the documentation
                        https://www.cvxpy.org/tutorial/advanced/index.html#mixed-integer-programs
                    for discussion on this topic.

                    Quick fix 1: if you install the python package CVXOPT (pip install cvxopt),
                    then CVXPY can use the open-source mixed-integer solver `GLPK`.

                    Quick fix 2: you can explicitly specify solver='ECOS_BB'. This may result
                    in incorrect solutions and is not recommended.

**Version**
 - OS: Mac OS
 - CVXPY Version: 1.3.0

**Additional context**

**Comment by SteveDiamond** [comment] 2022-03-14 20:56
Are you certain GLPK is installed? Try running ``from cvxopt import glpk``.

**Comment by rileyjmurray** [comment] 2022-03-15 00:39
@SteveDiamond @sarahboufelja the problem is that GLPK doesn't support nonlinear problems. You should install SCIP if you want to solve a mixed-integer nonlinear problem with an open-source solver. See below for how I update SCIP on my machine:

```
(cvx39) riley@borneophant:~$ conda install pyscipopt
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/riley/anaconda3/envs/cvx39

  added / updated specs:
    - pyscipopt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyscipopt-4.1.0            |   py39h5a03fae_0         698 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         698 KB

The following packages will be UPDATED:

  pyscipopt                            4.0.0-py39he80948d_0 --> 4.1.0-py39h5a03fae_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
pyscipopt-4.1.0      | 698 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
Then it's very easy to solve the problem
```
(cvx39) riley@borneophant:~$ python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy as cp
(CVXPY) Mar 14 05:36:27 PM: Encountered unexpected exception importing solver MOSEK:
AttributeError("module 'mosek' has no attribute 'conetype'")
im>>> import numpy as np
>>> np.random.seed(0)
>>> m, n= 40, 25
>>> 
>>> A = np.random.rand(m, n)
>>> b = np.random.randn(m)
>>> x = cp.Variable(n, integer=True)
>>> objective = cp.Minimize(cp.sum_squares(A @ x - b))
>>> prob = cp.Problem(objective)
>>> prob.solve(verbose=True)
===============================================================================
                                     CVXPY                                     
                            v1.3.0.dev0+347.a86ebf7                            
===============================================================================
(CVXPY) Mar 14 05:36:53 PM: Your problem has 25 variables, 0 constraints, and 0 parameters.
(CVXPY) Mar 14 05:36:53 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Mar 14 05:36:53 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Mar 14 05:36:53 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Mar 14 05:36:53 PM: Compiling problem (target solver=SCIP).
(CVXPY) Mar 14 05:36:53 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> SCIP
(CVXPY) Mar 14 05:36:53 PM: Applying reduction Dcp2Cone
(CVXPY) Mar 14 05:36:53 PM: Applying reduction CvxAttr2Constr
(CVXPY) Mar 14 05:36:53 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Mar 14 05:36:53 PM: Applying reduction SCIP
(CVXPY) Mar 14 05:36:53 PM: Finished problem compilation (took 8.844e-02 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Mar 14 05:36:53 PM: Invoking solver SCIP  to obtain a solution.
presolving:
   (0.0s) symmetry computation started: requiring (bin +, int +, cont +), (fixed: bin -, int -, cont -)
   (0.0s) no symmetry present
presolving (0 rounds: 0 fast, 0 medium, 0 exhaustive):
 0 deleted vars, 0 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolved problem has 68 variables (0 bin, 25 int, 0 impl, 43 cont) and 43 constraints
     42 constraints of type <linear>
      1 constraints of type <nonlinear>
Presolving Time: 0.00

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
  0.0s|     1 |     0 |    43 |     - |  1648k |   0 | 110 |  43 |  42 |   0 |  0 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    45 |     - |  1689k |   0 | 110 |  43 |  44 |   2 |  1 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    46 |     - |  1694k |   0 | 110 |  43 |  45 |   3 |  2 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    47 |     - |  1698k |   0 | 110 |  43 |  46 |   4 |  3 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    48 |     - |  1703k |   0 | 110 |  43 |  47 |   5 |  4 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    49 |     - |  1707k |   0 | 110 |  43 |  48 |   6 |  5 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    50 |     - |  1712k |   0 | 110 |  43 |  49 |   7 |  6 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    51 |     - |  1717k |   0 | 110 |  43 |  50 |   8 |  7 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    52 |     - |  1722k |   0 | 110 |  43 |  51 |   9 |  8 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    53 |     - |  1727k |   0 | 110 |  43 |  52 |  10 |  9 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    54 |     - |  1732k |   0 | 110 |  43 |  53 |  11 | 10 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     0 |    55 |     - |  1737k |   0 | 110 |  43 |  54 |  12 | 11 |   0 |   0 |-1.000000e+00 |      --      |    Inf | unknown
  0.0s|     1 |     2 |    55 |     - |  1756k |   0 | 110 |  43 |  54 |  12 | 11 |   0 |  25 |-1.000000e+00 |      --      |    Inf | unknown
  1.3s|   100 |   101 | 35415 | 357.2 |  7799k |  13 | 110 |  43 | 607 |  12k|  5 |   0 | 123 | 1.025074e+01 |      --      |    Inf | unknown
  2.7s|   200 |   201 | 80148 | 402.5 |    15M |  23 | 110 |  43 | 949 |  25k|  5 |   0 | 137 | 1.025074e+01 |      --      |    Inf | unknown
 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
  4.1s|   300 |   301 |123860 | 414.1 |    21M |  25 | 110 |  43 | 834 |  37k|  5 |   0 | 160 | 1.095518e+01 |      --      |    Inf | unknown
  5.5s|   400 |   401 |163926 | 410.7 |    26M |  27 | 110 |  43 | 983 |  47k|  4 |   0 | 179 | 1.096711e+01 |      --      |    Inf | unknown
  6.8s|   500 |   501 |206025 | 412.8 |    31M |  27 | 110 |  43 | 564 |  58k|  5 |   0 | 197 | 1.096711e+01 |      --      |    Inf | unknown
  8.1s|   600 |   601 |246239 | 411.0 |    36M |  29 | 110 |  43 |1124 |  68k|  4 |   0 | 210 | 1.096711e+01 |      --      |    Inf | unknown
  9.3s|   700 |   701 |287332 | 411.0 |    41M |  29 | 110 |  43 | 958 |  79k|  3 |   0 | 222 | 1.096711e+01 |      --      |    Inf | unknown
 10.5s|   800 |   801 |322510 | 403.6 |    46M |  41 | 110 |  43 | 957 |  88k|  2 |   0 | 234 | 1.096711e+01 |      --      |    Inf | unknown
*10.7s|   819 |   742 |327652 | 400.5 |    LP  |  41 | 110 |  43 |1607 |  90k|  7 |   0 | 235 | 1.096711e+01 | 4.848174e+01 | 342.06%|  27.50%
*11.1s|   873 |   472 |341146 | 391.2 |    LP  |  41 | 110 |  43 |1370 |  93k|  6 |   0 | 240 | 1.096711e+01 | 1.942214e+01 |  77.09%|  27.51%
*11.2s|   887 |   105 |343543 | 387.7 |    LP  |  41 | 110 |  43 |1065 |  94k|  7 |   0 | 240 | 1.096711e+01 | 1.366000e+01 |  24.55%|  29.38%
 11.4s|   900 |   106 |347580 | 386.6 |    49M |  41 | 110 |  49 | 877 |  95k|  4 |   7 | 244 | 1.096711e+01 | 1.366000e+01 |  24.55%|  30.51%
 12.2s|  1000 |   126 |374547 | 374.9 |    50M |  41 | 110 |  62 | 633 | 103k|  5 |  20 | 249 | 1.168656e+01 | 1.366000e+01 |  16.89%|  39.46%
 13.0s|  1100 |   142 |400933 | 364.8 |    51M |  41 | 110 |  75 | 671 | 110k|  5 |  33 | 254 | 1.182075e+01 | 1.366000e+01 |  15.56%|  49.02%
 13.7s|  1200 |   132 |424338 | 353.9 |    52M |  41 | 110 |  95 | 620 | 116k|  1 |  53 | 262 | 1.211446e+01 | 1.366000e+01 |  12.76%|  56.73%
 14.5s|  1300 |   128 |446734 | 343.9 |    54M |  41 | 110 | 107 | 631 | 122k|  5 |  65 | 267 | 1.223388e+01 | 1.366000e+01 |  11.66%|  62.81%
 15.1s|  1400 |   106 |467262 | 334.0 |    54M |  41 | 110 | 117 | 544 | 127k|  0 |  84 | 275 | 1.239619e+01 | 1.366000e+01 |  10.20%|  71.85%
 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
 15.8s|  1500 |    98 |489213 | 326.3 |    55M |  41 | 110 | 117 | 578 | 133k|  2 |  94 | 279 | 1.251554e+01 | 1.366000e+01 |   9.14%|  76.19%
 16.4s|  1600 |    60 |506177 | 316.5 |    55M |  41 | 110 | 117 | 458 | 137k|  0 | 108 | 281 | 1.264213e+01 | 1.366000e+01 |   8.05%|  85.19%
 16.9s|  1700 |     8 |520577 | 306.4 |    57M |  41 | 110 | 117 | 607 | 140k|  0 | 127 | 283 | 1.284963e+01 | 1.366000e+01 |   6.31%|  97.28%

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 17.01
Solving Nodes      : 1714
Primal Bound       : +1.36600032146618e+01 (3 solutions)
Dual Bound         : +1.36600032146618e+01
Gap                : 0.00 %
-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Mar 14 05:37:10 PM: Problem status: optimal
(CVXPY) Mar 14 05:37:10 PM: Optimal value: 1.366e+01
(CVXPY) Mar 14 05:37:10 PM: Compilation took 8.844e-02 seconds
(CVXPY) Mar 14 05:37:10 PM: Solver (including time spent in interface) took 1.709e+01 seconds
13.660003257778833
```
Let us know if you have any further problems!

**Comment by rileyjmurray** [comment] 2022-03-15 00:41
Re-opening since others might run into this problem. We should update the page

https://www.cvxpy.org/examples/basic/mixed_integer_quadratic_program.html

**Comment by sarahboufelja** [comment] 2022-03-17 11:44
Thank you, works now with SCIP.

**Comment by rileyjmurray** [comment] 2022-04-02 19:53
I'm working on a PR to update this example page. I'm not closing this issue because we might want to change the the solver error message from
``` 
        You need a mixed-integer solver for this model. Refer to the documentation
            https://www.cvxpy.org/tutorial/advanced/index.html#mixed-integer-programs
        for discussion on this topic.

        Quick fix 1: if you install the python package CVXOPT (pip install cvxopt),
        then CVXPY can use the open-source mixed-integer solver `GLPK`.

        Quick fix 2: you can explicitly specify solver='ECOS_BB'. This may result
        in incorrect solutions and is not recommended.
```
to 
``` 
        You need a mixed-integer solver for this model. Refer to the documentation
            https://www.cvxpy.org/tutorial/advanced/index.html#mixed-integer-programs
        for discussion on this topic.

        Quick fix 1: if you install the python package CVXOPT (pip install cvxopt),
        then CVXPY can use the open-source mixed-integer linear programming
        solver `GLPK`. If your problem is nonlinear then you can install SCIP
        (pip install pyscipopt). 

        Quick fix 2: you can explicitly specify solver='ECOS_BB'. This may result
        in incorrect solutions and is not recommended.
```

**Closed** 2022-04-03 21:07 UTC
