### ISSUE TITLE
Numerical issues in least squares problem with nearly-dependent rows

### ISSUE THREAD

**Issue by snio89** [cvxpy/cvxpy#2005] opened 2023-01-10 08:19 UTC
**Describe the bug**

CVXPY cannot solve a specific problem and identifies it as a unbounded problem.
However, after applying the weighting factor to the objective matrices, CVXPY successfully solves the same problem.

**To Reproduce**

```
import numpy as np
import cvxpy as cp

weight = 100

x = cp.Variable(7)
A = np.array(
    [[ 0.176121, 0.150591, 0.128763, 0.110098, 0.094139, 0.080493, -1],
    [ 0.180449, 0.154426, 0.132156, 0.113098, 0.096788, 0.082830, -1],
    [ 0.170260, 0.145456, 0.124266, 0.106163, 0.090697, 0.077484, -1],
    [ 0.177728, 0.151878, 0.129787, 0.110910, 0.094779, 0.080993, -1],
    [ 0.180519, 0.154379, 0.132024, 0.112906, 0.096556, 0.082574, -1],
    [ 0.180449, 0.154384, 0.132085, 0.113006, 0.096683, 0.082718, -1],
    [ 0.180285, 0.153893, 0.131364, 0.112133, 0.095718, 0.081705, -1],
    [ 0.175608, 0.150123, 0.128337, 0.109712, 0.093790, 0.080179, -1],
    [ 0.177658, 0.151711, 0.129554, 0.110633, 0.094475, 0.080677, -1],
    [ 0.179487, 0.153126, 0.130637, 0.111450, 0.095082, 0.081117, -1],]
)

b = np.array(
    [3.199546, 3.449552, 3.491471, 3.354685, 3.517363, 3.275519, 3.414937, 3.502791, 3.369826, 3.408456]
)

A = A / weight
b = b / weight

obj = cp.Minimize(cp.sum(cp.huber(A @ x - b)))
const = [x[-1] >= -10, x[-1] <= 10]

prob = cp.Problem(obj, const)
prob.solve(solver=cp.OSQP)

print(prob.status)
```

**Expected behavior**

CVXPY may or may not solve this problem. The solving behavior is independent to the weighting factor.

**Output**

If `weight = 1`: print `unbounded`.
If `weight = 100`: print `optimal`.

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.3.0

**Additional context**

I am sorry for posting my specific problem.
It is weired that the result of the CVXPY operation (with solvers OSQP or CVXOPT) depends on the weighting factor.
This behavior may be related to the characteristic of the objective matrix and floating point precision.

**Comment by aszekMosek** [comment] 2023-01-10 10:06
This is a numerical issue caused by the fact that the rows of A are almost equal and that makes the problem numerically hard due to near linear dependencies. All solvers I tried struggle in one way or another even if you just optimize ``cp.sum_squares(A@x-b)`` ie. ordinary regression and the solutions one gets, if any, are all over the place. Whether one or another solver will fail for one or another weight with one or another message is a secondary issue.

**Comment by snio89** [comment] 2023-01-13 04:38
Thanks for providing a detailed explanation (and sorry for my late response). It seems like linear dependency check methods, such as singular value decomposition, are required for me.

**Comment by aszekMosek** [comment] 2023-01-13 08:40
I think the issue with your example is that you are doing (essentially) linear regression on a set of points that are clumped all very close together, and then every regression line/plane is almost just as good so it is hard to converge to one of them.

**Comment by rileyjmurray** [comment] 2023-05-14 02:27
Closing as off-topic, per aszekMosek's comments.

**Closed by rileyjmurray** 2023-05-14 02:27 UTC
