### ISSUE TITLE
CVXOPT solver gives unbounded message while CVXOPT package gives feasible solution

### ISSUE THREAD

**Issue by Dr4cky** [cvxpy/cvxpy#2011] opened 2023-01-16 10:34 UTC
Hi there,

I have been trying to solve a quadratic optimization problem. I have tried all the open source solvers as well as MOSEK. I noticed that OSQP, Clarabel and PROXQP result in a feasible solution, but that ECOS/CVXOPT/MOSEK do not. 

I decided to use the CVXOPT package, solver qp just to see if that would give me more information about why it is not feasible. I did not expect it to return a feasible solution.

Any ideas why the results differ?

```
# cvxopt
A = np.r_[A_inv_lb, A_inv_ub,
          A_init_inv.values.reshape(1, -1),
          A_cash,
          -A_cash,
          A_DV01, -A_DV01]
b = np.r_[b_inv_lb, b_inv_ub,
          b_init_inv,
          b_cash_ub+A_cash_l,
          -b_cash_lb-A_cash_l,
          b_DV01_ub - A_DV01_l, -b_DV01_lb + A_DV01_l]

P = matrix(H_symmetric)
q = matrix(F)
G = matrix(A)
h = matrix(b)        

sol = solvers.qp(P,q,G,h)
sol['x']

# cvxpy
#%%
constraints = [A @ y <= b]
objective = cp.Minimize(0.5*cp.quad_form(y, H_symmetric, True) + F.T @ y)
prob = cp.Problem(objective, constraints)
prob.solve(verbose=True, solver='CVXOPT')
```

Thanks!

**Comment by aszekMosek** [comment] 2023-01-16 11:54
Since conic solvers say infeasible and QP solvers say feasible it may have something to do with how the quadratic form is factorized. It would suggest that your model has some nasty numerical property.

That is very likely all that can be said without a reproducible example with data.

**Comment by michaels0m** [comment] 2023-01-29 18:46
I believe this issue is related to an older one I opened a while ago: https://github.com/cvxpy/cvxpy/issues/1186

I would be happy to help implement any warnings about badly scaled problems. @aszekMosek - if you have any suggestions for checks or materials regarding scaling QP problems please send them over!

**Comment by rileyjmurray** [comment] 2023-11-04 15:37
We can help more via Discord if needed. For now I'm marking as closed, but pointing an open issue back to this one.

**Closed by rileyjmurray** 2023-11-04 15:37 UTC
