### ISSUE TITLE
pip installation failure

### ISSUE THREAD

**Issue by azurewtl** [cvxpy/cvxpy#1765] opened 2022-05-02 07:32 UTC
Im trying to install optbinning in my M1 Mac book pro, whereas the dependency "cvxpy" is fail to be installed
The reason might be: It required numpy-1.16.6, but I checked numpy-1.16.6 only support python3.7

Related code:https://github.com/cvxpy/cvxpy/blob/0c657756d34592bf5a567d2a545b26e86da99208/pyproject.toml#L18
Python: 3.8.12
OS: macOS Monterey Version 12.3.1

<=====Error Message=====>

MacBook-Pro ~ % pip install cvxpy --no-deps
Collecting cvxpy
  Downloading cvxpy-1.2.0.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 4.7 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3057 lines of output]
      Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and (platform_machine == "arm64" and platform_system == "Darwin")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and (platform_machine != "arm64" or platform_system != "Darwin")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and (platform_machine == "arm64" and platform_system == "Darwin")' don't match your environment
      Collecting numpy<1.17,>=1.16
        Downloading numpy-1.16.6.zip (5.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 9.0 MB/s eta 0:00:00
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting scipy>=1.1.0
        Downloading scipy-1.8.0-cp38-cp38-macosx_12_0_arm64.whl (28.5 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.5/28.5 MB 3.3 MB/s eta 0:00:00
.....
.....
.....
.....
.....
.....
/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> numpy
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by matteosantama** [comment] 2022-05-07 01:11
Are you able to `pip install 'numpy==1.16'` on your machine? I believe the problem is that `numpy==1.16` cannot be installed on an M1.

**Comment by rileyjmurray** [comment] 2022-05-07 04:09
Thanks for the input @matteosantama, that might indeed be a problem here. Looking at the NumPy PyPI page (here https://pypi.org/project/numpy/1.16.6/#files), it's true that there are no wheels for Python 3.8. That means pip will try to build version 1.16 for Python 3.8 from NumPy source code, which leads to an inevitable failure.

We could add another case-check to pyproject.toml so that M1 macs need a higher version of NumPy when installing on Python 3.7 or 3.8.

**Comment by rileyjmurray** [comment] 2022-05-07 04:12
@azurewtl you might try following the suggestion at https://github.com/cvxpy/cvxpy/issues/1190#issuecomment-990418512 to override cvxpy's pyproject.toml.

**Comment by maitreyeemarathe** [comment] 2022-06-02 23:39
Update - I was able to install cvxpy using conda (and Python 3.10.4) instead of pip. I installed cvxopt with conda and then cvxpy.

**Comment by SteveDiamond** [comment] 2022-06-13 04:30
Resolved via #1799 and #1800.

**Closed by SteveDiamond** 2022-06-13 04:30 UTC
