### ISSUE TITLE
log_det for complex psd matrix

### ISSUE THREAD

**Issue by xinyanglii** [cvxpy/cvxpy#1816] opened 2022-07-04 14:40 UTC
**Describe the bug**
Hi cvxpy team,

I found that in the log_det function, the input matrix is treated as a real positive semidefinite (PSD) matrix. If the input is a complex matrix, the result turns out to be -np.inf, due to these lines:
```
symm = (values[0] + values[0].T)/2
sign, logdet = LA.slogdet(symm)
if sign == 1:
    return logdet
else:
    return -np.inf
```

In addition, as far as I know, PSD matrices are always considered as real matrics in cvxpy. It might lead to unexpected results if they are as well specified as complex. Since complex PSD matrices are very commonly used in many areas like wireless communication, it would be great if cvxpy could handle it in the future.

**To Reproduce**
A small example for the problem of log_det function:

```
import cvxpy as cp

X = cp.Variable(shape = (3,3),
            complex = True)


cons = [X>>0, cp.real(cp.trace(X))<=9]
obj = cp.Maximize(cp.log_det(X))

prob = cp.Problem(objective=obj, constraints=cons)

prob.solve()
print(prob.value)
print(X.value)

```

and it gives -np.inf as the optimal objective value although `X` is the solved correctly, which is diag{3, 3, 3}. 

**Output**
```
-inf
[[3.00000000e+00+0.00000000e+00j 1.41069594e-15-5.53050530e-16j
  3.72971957e-16-6.41441562e-16j]
 [1.41069594e-15+5.53050529e-16j 3.00000000e+00+0.00000000e+00j
  2.88571453e-15+1.42317559e-15j]
 [3.72971957e-16+6.41441563e-16j 2.88571453e-15-1.42317559e-15j
  3.00000000e+00+0.00000000e+00j]]
```

**Version**
 - OS: Windows 11
 - CVXPY Version: 1.2.1

**Comment by rileyjmurray** [comment] 2022-07-04 20:30
Thanks for reporting! This is indeed a bug.  I believe it can be fixed by replacing ``symm = (values[0] + values[0].T)/2`` by ``symm = (values[0] + values[0].H)/2``.

**Comment by HejaFCB** [comment] 2022-07-05 09:02
Hi, Thank you for the quick reply. I changed the source codes accordingly, however the output `prob.value` is still `-inf`.

**Comment by rileyjmurray** [comment] 2022-08-14 01:05
The problem is that ``slogdet(X.value)`` is returning ``
((1+4.4360003524880695e-30j), 3.29583684600172)``. So what we should do is check that the matrix is Hermitian to within some specified tolerance, return ``-inf`` if not, and then check that the real part of ``slogdet(a)[0]`` is 1.

**Closed** 2022-11-23 03:45 UTC
Labels: bug
